//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VC Tester.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_VCTESTER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_PRINT_DIALOG                132
#define IDD_OUTPUTXY_DIALOG             135
#define IDD_VALIDATEBARCODE_DIALOG      136
#define IDD_ZOOM_DIALOG                 138
#define IDD_FINDOBJECT_DIALOG           139
#define IDD_ADDOBJECT_DIALOG            141
#define IDD_TEXT_OBJECT_DIALOG          142
#define IDD_ADDRESS_OBJECT_DIALOG       143
#define IDD_GRAPHIC_OBJECT_DIALOG       144
#define IDD_RECTANGLE_OBJECT_DIALOG     145
#define IDD_LINE_OBJECT_DIALOG          146
#define IDD_BARCODE_OBJECT_DIALOG       147
#define IDR_POPUP_MENU                  147
#define IDB_SAMPLE_BITMAP               147
#define IDD_COUNTER_OBJECT_DIALOG       148
#define IDD_DATETIME_OBJECT_DIALOG      149
#define IDD_WINDOWS_DIALOG              150
#define ID_CLOSE                        1000
#define IDC_LABEL_LIST                  1001
#define IDC_LABELS_LIST                 1001
#define IDC_LABEL_INFO                  1004
#define IDC_STATIC_PICTURE              1007
#define IDC_LOAD_BUTTON                 1009
#define IDC_SAVE_BUTTON                 1010
#define IDC_PRINT_LABEL_BUTTON          1011
#define IDC_OUTPUT_BUTTON               1012
#define IDC_OUTPUTXY_BUTTON             1013
#define IDC_VALIDATEBARCODE_BUTTON      1014
#define IDC_COPYTO_BUTTON               1015
#define IDC_PASTEFROM_BUTTON            1016
#define IDC_DEVICE_NAME                 1017
#define IDC_PORT                        1018
#define IDC_QUANTITY                    1019
#define IDC_SHOWDIALOG                  1021
#define IDC_QUANTITY_SPIN               1023
#define IDC_X                           1024
#define IDC_Y                           1025
#define IDC_TEXT                        1026
#define IDC_BCTYPE                      1027
#define IDC_XC                          1029
#define IDC_YC                          1030
#define IDC_OBJECTS_BUTTON              1031
#define IDC_OBJECTS_LIST                1032
#define IDC_ZOOM_BUTTON                 1033
#define IDC_ZOOM                        1034
#define IDC_VAROBJECTS_BUTTON           1034
#define IDC_SHADOW_CHECK                1035
#define IDC_OBJECTNAME                  1036
#define IDC_BRINGTOFRONT_BUTTON         1036
#define IDC_FINDOBJECT_BUTTON           1037
#define IDC_ADDROTATION                 1037
#define IDC_SENDTOBACK_BUTTON           1038
#define IDC_ADDHEIGHT                   1038
#define IDC_DELETE_BUTTON               1039
#define IDC_ADDWIDTH                    1039
#define IDC_ADDOBJECT_BUTTON            1040
#define IDC_ADDY                        1040
#define IDC_ADDX                        1041
#define IDC_GENERAL_BUTTON              1041
#define IDC_ADDNAME                     1042
#define IDC_SPECIAL_BUTTON              1042
#define IDC_OBJECTAT_BUTTON             1043
#define IDC_OBJTYPE                     1044
#define IDC_OBJECTSAT_BUTTON            1044
#define IDC_TEXTOBJ_TEXTCOLOR           1044
#define IDC_GETMODIFIED_BUTTON          1045
#define IDC_TEXTOBJ_BACKGROUNDCOLOR     1045
#define IDC_TEXTOBJ_MIRRORED            1047
#define IDC_TEXTOBJ_VERTICAL            1048
#define IDC_TEXTOBJ_ISVARIABLE          1049
#define IDC_TEXTOBJ_TEXT                1050
#define IDC_TEXTOBJ_FONT1               1051
#define IDC_TEXTOBJ_FONT2               1052
#define IDC_TEXTOBJ_JUSTIFY             1053
#define IDC_TEXTOBJ_VJUSTIFY            1054
#define IDC_ADDRESSOBJ_TEXT             1055
#define IDC_ADDRESSOBJ_FONT1            1056
#define IDC_ADDRESSOBJ_FONT2            1057
#define IDC_ADDRESSOBJ_JUSTIFY          1058
#define IDC_ADDRESSOBJ_VJUSTIFY         1059
#define IDC_ADDRESSOBJ_MIRRORED         1060
#define IDC_ADDRESSOBJ_VERTICAL         1061
#define IDC_ADDRESSOBJ_TEXTCOLOR        1062
#define IDC_ADDRESSOBJ_BACKGROUNDCOLOR  1063
#define IDC_ADDRESSOBJ_BARCODEPOSITION  1064
#define IDC_GRAPHICOBJ_GRAPHICSOURCE    1064
#define IDC_ADDRESSOBJ_B9DIGITONLY      1065
#define IDC_GRAPHICOBJ_FILENAME         1065
#define IDC_GRAPHICOBJ_BITMAPHANDLE     1066
#define IDC_GRAPHICOBJ_PALETTEHANDLE    1067
#define IDC_GRAPHICOBJ_WINDOWHANDLE     1068
#define IDC_GRAPHICOBJ_BORDER           1069
#define IDC_GRAPHICOBJ_BORDERCOLOR      1070
#define IDC_FILENAME_CHANGE             1071
#define IDC_BITMAP_CHANGE               1072
#define IDC_WINDOWHANDLE_CHANGE         1073
#define IDC_GRABCLIPBOARD               1074
#define IDC_BFILLED                     1075
#define IDC_RECTANGLEOBJ_BORDER         1076
#define IDC_RECTANGLEOBJ_BORDERCOLOR    1077
#define IDC_RECTANGLEOBJ_FILLCOLOR      1078
#define IDC_LINEOBJ_ORIENTATION         1079
#define IDC_LINEOBJ_LENGTH              1080
#define IDC_LINEOBJ_THICKNESS           1081
#define IDC_LINEOBJ_LINECOLOR           1082
#define IDC_BARCODEOBJ_TEXT             1083
#define IDC_BARCODEOBJ_FONT             1084
#define IDC_BARCODEOBJ_TEXTPOS          1085
#define IDC_BARCODEOBJ_BCTYPE           1086
#define IDC_BARCODEOBJ_SIZE             1087
#define IDC_COUNTEROBJ_PRETEXT          1087
#define IDC_BARCODEOBJ_JUSTIFY          1088
#define IDC_COUNTEROBJ_TEXT             1088
#define IDC_BARCODEOBJ_LINK             1089
#define IDC_COUNTEROBJ_FONT1            1089
#define IDC_COUNTEROBJ_FONT2            1090
#define IDC_COUNTEROBJ_JUSTIFY          1091
#define IDC_COUNTEROBJ_VJUSTIFY         1092
#define IDC_COUNTEROBJ_MIRRORED         1093
#define IDC_COUNTEROBJ_VERTICAL         1094
#define IDC_COUNTEROBJ_TEXTCOLOR        1095
#define IDC_COUNTEROBJ_BACKGROUNDCOLOR  1096
#define IDC_COUNTEROBJ_POSTTEXT         1097
#define IDC_COUNTEROBJ_START            1098
#define IDC_COUNTEROBJ_CURRENT          1099
#define IDC_COUNTEROBJ_WIDTH            1100
#define IDC_COUNTEROBJ_INCREMENT        1101
#define IDC_COUNTEROBJ_USELEADINGZEROS  1102
#define IDC_DATETIMEOBJ_TEXT            1103
#define IDC_DATETIMEOBJ_FONT1           1104
#define IDC_DATETIMEOBJ_FONT2           1105
#define IDC_DATETIMEOBJ_JUSTIFY         1106
#define IDC_DATETIMEOBJ_VJUSTIFY        1107
#define IDC_DATETIMEOBJ_MIRRORED        1108
#define IDC_DATETIMEOBJ_VERTICAL        1109
#define IDC_DATETIMEOBJ_TEXTCOLOR       1110
#define IDC_DATETIMEOBJ_BACKGROUNDCOLOR 1111
#define IDC_DATETIMEOBJ_PRETEXT         1112
#define IDC_DATETIMEOBJ_POSTTEXT        1113
#define IDC_DATETIMEOBJ_FORMAT          1114
#define IDC_DATETIMEOBJ_INCLUDETIME     1115
#define IDC_DATETIMEOBJ_B24HOUR         1116
#define IDC_WINDOWS_LIST                1116
#define IDC_LI_LABELNAME                1117
#define IDC_LI_PAPERNAME                1118
#define IDC_LI_PAPERWIDTH               1119
#define IDC_LI_PAPERHEIGHT              1120
#define IDC_LI_BITMAPWIDTH              1121
#define IDC_LI_BITMAPHEIGHT             1122
#define IDC_LI_LABELCOUNT               1123
#define IDC_LI_LABELWIDTH               1124
#define IDC_LI_LABELHEIGHT              1125
#define IDC_LI_MODIFIED                 1126
#define IDC_LBL_LABELLIST               1127
#define ID_OBJECT_AT                    32772
#define ID_OBJECTS_AT                   32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1128
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
